import Head from "next/head"
import { useRouter } from "next/router"
import { useEffect } from "react"
import AppLayout from "components/AppLayout"
import Button from "components/Button"
import Github from "components/Icons/Github"
import { colors } from "styles/theme"
import { loginWithGithub } from "firebase/client"
import useUser, { USER_STATES } from "hooks/useUser"

export default function Home() {
  const user = useUser()
  const router = useRouter()

  useEffect(() => {
    user && router.replace("/home")
  }, [user])

  const handleLogin = () => {
    loginWithGithub().catch((error) => {
      console.log(error)
    })
  }

  return (
    <>
      <Head>
        <title>devtter 🍕</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <section>
          <img src="/devter-logo.png" alt="Logo" />
          <h1>Devtter</h1>
          <h2>Talk about development with developers 🧑👧</h2>
          <div>
            {user === USER_STATES.NOT_LOGGED && (
              <Button onClick={handleLogin}>
                <Github fill={colors.white} width={24} height={24} />
                Login with Github
              </Button>
            )}
            {user === USER_STATES.NOT_KNOWS && <span>Loading ....</span>}
          </div>
        </section>
      </AppLayout>
      <style jsx>{`
        img {
          width: 120px;
        }
        div {
          margin-top: 16px;
        }
        section {
          display: grid;
          height: 100%;
          place-content: center;
          place-items: center;
        }
        h1 {
          color: ${colors.primary};
          font-weight: 800;
          margin-bottom: 16px;
        }
        h2 {
          color: ${colors.secondary};
          font-size: 21px;
          margin: 0;
        }
        span {
          color: ${colors.primary};
        }
      `}</style>
    </>
  )
}
